services:

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  celery:
    build:
      context: .
      dockerfile: Dockerfile

    command: >
      celery -A elearning_app worker
      --loglevel=info
      --pool=solo

    volumes:
      - .:/app

    environment:
      CELERY_BROKER_URL: redis://redis:6379/1

    depends_on:
      - redis

volumes:
  redis_data: