# Generated by Django 6.0.7 on 2026-08-26 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_statusupdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statusupdate',
            options={'ordering': ['-created_at']},
        ),
    ]
