# Generated by Django 6.0.7 on 2026-08-26 09:32

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='courseblock',
            options={'ordering': ['-blocked_at']},
        ),
        migrations.AlterModelOptions(
            name='coursematerial',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='enrolment',
            options={'ordering': ['-enrolled_at']},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='courseblock',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='enrolment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='coursematerial',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddConstraint(
            model_name='courseblock',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='unique_course_block'),
        ),
        migrations.AddConstraint(
            model_name='enrolment',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='unique_student_enrolment'),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='unique_student_course_feedback'),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='feedback_rating_between_1_and_5'),
        ),
        migrations.RemoveField(
            model_name='courseblock',
            name='teacher',
        ),
    ]
