# Generated by Django 6.0.7 on 2026-09-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_options_alter_courseblock_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('computer_science', 'Computer Science'), ('programming', 'Programming'), ('web_development', 'Web Development'), ('databases', 'Databases'), ('artificial_intelligence', 'Artificial Intelligence'), ('cybersecurity', 'Cybersecurity'), ('software_engineering', 'Software Engineering'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
