# Generated by Django 6.0.7 on 2026-08-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('enrolment', 'Enrolment'), ('material', 'New Material')], default='enrolment', max_length=20),
        ),
    ]
