# Generated by Django 6.0.7 on 2026-09-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('enrolment', 'Enrolment'), ('material', 'Material'), ('block', 'Course Blocked'), ('unblock', 'Course Unblocked')], max_length=20),
        ),
    ]
