# Generated by Django 6.0.7 on 2026-09-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('enrolment', 'Course Enrolment'), ('material', 'New Material'), ('block', 'Course Blocked'), ('unblock', 'Course Unblocked'), ('remove', 'Removed from Course')], max_length=20),
        ),
    ]
